
name: sharedPtr CI

on: [push, pull_request]

jobs:
  sharedPtr:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir build
      working-directory: homework/shared_ptr
      run: mkdir build
    - name: Compile
      working-directory: homework/shared_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: homework/shared_ptr/build
      run:  ctest -V

  ut_valgrind:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install valgrind
      run: sudo apt-get install valgrind
    - name: mkdir build
      working-directory: homework/shared_ptr
      run: mkdir build
    - name: Compile
      working-directory: homework/shared_ptr/build
      run: |
        cmake ..
        make
    - name: Run valgrind
      working-directory: homework/shared_ptr/build
      run: valgrind --leak-check=full --show-leak-kinds=all ./SharedPtr-ut